# Generated by Django 3.1.2 on 2020-10-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_1', models.IntegerField(db_column='s_1', default=-214748)),
                ('s_2', models.IntegerField(db_column='s_2', default=-214748)),
                ('s_3', models.IntegerField(db_column='s_3', default=-214748)),
                ('time_date', models.CharField(db_column='time_date', max_length=255)),
            ],
        ),
    ]
